
sudo: required
language: java

jdk:
  - oraclejdk8
  - openjdk7



script:
  - mvn clean cobertura:cobertura -Dtest=SimpleFlowTest#testFlowWithSameInputNameAsStep -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/cloud-slang/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "wAWU1dR5Bc3BYFjZjPvp2bMOZustY+2uf/1WGBti27B4hmGfqoZmLO11mCJuQQJVehgO715/bUED0nn4kw0CLYJagxVulkoE1fNY/JWHCbbP6EkCYwKflKxiYfGjkHP/dFsZixM4fUrqbdrQ9FqoQ2ftIv/eG9JBLv0B7r9r1pP9sidNaKNsSx0BeL+vk0DSvhP3MM4jU66RK7qxHlZMcuJFkRko8H0Oy0q2+u59c4ExXLvQeJlGQVFS2lFrkAAXm4t8GdwwPvUjJxui6+Kf9Mc8+7z4H3XNLV0ct2CAYm37Qhi8yGZBd1WdMjhWPkY/BN5t/c/q+n/ZYcuQcdi9uhfFCkpoNPajzyI4NHEV4u6Cgl68VJrQ+RyLBLnQhQpptZCxNtPqMyrbSTO2eg7t6nSx8knonzxqyAHrwKrP3dfii8LZktZnZ7eW+QWmc6eVRguAu57N1ffE2EIfJL+hy+rAcr6idLTv2EuOMVhvQnOeemaKP/Zj81yC+XA2qTflIdOvwqsaOZHUjYcsTEmUcafh31h/sMoiCdx1f0AsJxinCMrO0rOKnOGMNNYjjyd6UOKRro2VjoFCJXkSPXCYq17UP8A72Tgpzkbpnxswy1yag2WvQFXMEblSCRkgAgo7dFNuLQ93Y+m0Xx2ZWzNXLbz9miXNauQgr+ZEqvqBKAE="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
