
sudo: required
language: java

jdk:
  - openjdk8









script:
  - mvn clean cobertura:cobertura -Dtest=java#UnsupportedOperationException -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/cloud-slang/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "szQmxkNp/8RbR2yZ3l1+D3J3rtzj39c85el8ER9elXiEjILfxxdSu2VJeuMBd6axOocFnK0z1wLP7MSQAUezQUsD6oLMKOyUUJWltqUzoBcIUw50R8wqOCzMebKyQe6ZWzjSXTDpp2OyjTFyw2JRw6kLS1YBoZ1lyxaAihV1x4uD+7fuVR5fvSqBvq7RsXSEKHSej1lzoJOP7dzI+YLh5uWuThizFVZ+6u73qOfkEfOsAwe36r3aYj6Ja728zBmxrru6HgsD+BQgkLJfaf8LJbrDPGutX09ONCzPav3ukVOoUvUrD74GiE6NEbHnEp2IVVRMAgtVzagtl9MwPy6fu+k/O1yU2gNRR9WfSsfAES6rK7S3Rh4FsK+rVzugHOo3Ka42kA8VvYX9EZWdl6nrv5uHr9SMR0q0Cx3pO5izkf+lreTEMoyp2hKNKjMyGwYxHFVyQhrjndzlYsjs2khNzO8Kz+ujrMb86Qa00zqi7DJCDddlUKnf0M6ZdsyBjc/QIxs+g0Q1l7W8vEYle9O96nMt0cTuM6tKZSLMBZ71egzGdcyVKV0LIUuxM6Cf+/MDqyp5ohWOL8OZ6ip1qspqL4yp7tkvekoWpLdCmjUm0iKdUx4bTMBd9ccq8ymkhOJePnwFTlFEZr8CeVNafKau07M19SWFUx/jBOvglvLxA+c="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
